# Generated by Django 5.1.5 on 2025-01-23 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id_addresse', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('voie', models.CharField(max_length=255)),
                ('complement', models.CharField(blank=True, max_length=255, null=True)),
                ('ville', models.CharField(max_length=255)),
                ('code_postale', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Plante',
            fields=[
                ('id_plante', models.AutoField(primary_key=True, serialize=False)),
                ('nom_plante', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TypeDemande',
            fields=[
                ('id_type_demande', models.AutoField(primary_key=True, serialize=False)),
                ('nom_type_demande', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id_utilisateur', models.AutoField(primary_key=True, serialize=False)),
                ('is_pro', models.BooleanField(default=False)),
                ('pseudo', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('adresse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pageprincipale.adresse')),
            ],
        ),
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_demande', models.DateTimeField()),
                ('plante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pageprincipale.plante')),
                ('type_demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pageprincipale.typedemande')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pageprincipale.utilisateur')),
            ],
            options={
                'unique_together': {('plante', 'utilisateur', 'type_demande')},
            },
        ),
    ]
