# Generated by Django 5.1.7 on 2025-04-03 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageprincipale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='pseudo',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
