# Generated by Django 5.1.5 on 2025-01-26 15:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageprincipale', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='plante',
            name='photo_plante',
            field=models.ImageField(blank=True, null=True, upload_to='photos_plantes/'),
        ),
        migrations.AddField(
            model_name='plante',
            name='utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plantes', to=settings.AUTH_USER_MODEL),
        ),
    ]
