# Generated by Django 5.2.3 on 2025-06-24 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageprincipale', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='adresse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pageprincipale.adresse'),
        ),
    ]
