# Generated by Django 5.1.5 on 2025-01-26 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageprincipale', '0002_plante_photo_plante_plante_utilisateur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plante',
            name='utilisateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plantes', to='pageprincipale.utilisateur'),
        ),
    ]
