# Generated by Django 5.1.5 on 2025-01-26 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageprincipale', '0003_alter_plante_utilisateur'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Demande_plante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('en attente', 'En attente'), ('acceptée', 'Acceptée'), ('refusée', 'Refusée')], default='en attente', max_length=20)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('date_reponse', models.DateTimeField(blank=True, null=True)),
                ('plante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pageprincipale.plante')),
                ('utilisateur_demandeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_envoyees', to=settings.AUTH_USER_MODEL)),
                ('utilisateur_receveur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_recues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
