# Generated by Django 5.1.5 on 2025-01-26 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageprincipale', '0005_demande_plante_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demande_plante',
            name='utilisateur_demandeur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_envoyees', to='pageprincipale.utilisateur'),
        ),
        migrations.AlterField(
            model_name='demande_plante',
            name='utilisateur_receveur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_recues', to='pageprincipale.utilisateur'),
        ),
    ]
