# Generated by Django 5.1.5 on 2025-01-28 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageprincipale', '0006_alter_demande_plante_utilisateur_demandeur_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id_message', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=500)),
                ('date_demande', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos_plantes/')),
                ('est_une_reponse', models.BooleanField(default=False)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pageprincipale.utilisateur')),
                ('reponse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pageprincipale.message')),
            ],
        ),
    ]
