# Generated by Django 5.1.4 on 2025-01-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageprincipale', '0007_utilisateur_latitude_utilisateur_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
