# Generated by Django 5.1.5 on 2025-01-28 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageprincipale', '0007_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='reponse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pageprincipale.message'),
        ),
    ]
