# Generated by Django 5.1.5 on 2025-01-28 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pageprincipale', '0008_alter_message_reponse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='est_une_reponse',
        ),
        migrations.RemoveField(
            model_name='message',
            name='reponse',
        ),
    ]
