# Generated by Django 5.1.5 on 2025-01-28 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageprincipale', '0009_remove_message_est_une_reponse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pageprincipale.utilisateur')),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='pageprincipale.message')),
            ],
        ),
    ]
