# Generated by Django 5.1.4 on 2025-01-29 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pageprincipale', '0008_alter_utilisateur_latitude_and_more'),
        ('pageprincipale', '0010_commentaire'),
    ]

    operations = [
    ]
