# Generated by Django 5.1.5 on 2025-01-29 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageprincipale', '0010_commentaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande_plante',
            name='photo_plante1',
            field=models.ImageField(blank=True, null=True, upload_to='photos_plantes/'),
        ),
        migrations.AddField(
            model_name='demande_plante',
            name='photo_plante2',
            field=models.ImageField(blank=True, null=True, upload_to='photos_plantes/'),
        ),
        migrations.AddField(
            model_name='demande_plante',
            name='photo_plante3',
            field=models.ImageField(blank=True, null=True, upload_to='photos_plantes/'),
        ),
    ]
