# Generated by Django 5.1.5 on 2025-01-29 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageprincipale', '0011_demande_plante_photo_plante1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos_plantes/')),
                ('Demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pageprincipale.demande_plante')),
            ],
        ),
    ]
