# Generated by Django 5.1.5 on 2025-01-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageprincipale', '0012_messageimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageimage',
            name='text',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
