# Generated by Django 5.1.5 on 2025-01-30 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pageprincipale', '0011_merge_20250129_1147'),
        ('pageprincipale', '0013_messageimage_text'),
    ]

    operations = [
    ]
