# Generated by Django 5.1.5 on 2025-01-30 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageprincipale', '0014_merge_0011_merge_20250129_1147_0013_messageimage_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demande_plante',
            name='photo_plante1',
        ),
        migrations.RemoveField(
            model_name='demande_plante',
            name='photo_plante2',
        ),
        migrations.RemoveField(
            model_name='demande_plante',
            name='photo_plante3',
        ),
        migrations.AddField(
            model_name='messageimage',
            name='utilisateur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pageprincipale.utilisateur'),
        ),
    ]
