# Generated by Django 5.1.5 on 2025-01-30 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pageprincipale', '0018_utilisateur_adress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='adress',
            new_name='adresse',
        ),
    ]
