# Generated by Django 5.1.5 on 2025-01-30 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageprincipale', '0020_remove_utilisateur_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='adresse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pageprincipale.adresse'),
        ),
    ]
