# Generated by Django 5.1.4 on 2025-03-14 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pageprincipale', '0021_alter_utilisateur_adresse'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande_plante',
            name='est_acceptee',
            field=models.BooleanField(default=False),
        ),
    ]
